import {getDeviceType} from "../../src/utilitaries/device.tsx";

export const __Sizes: any = [
    {
        fullScreenPage_topBar_left: 20,
        fullScreenPage_topBar_right: 20,
        fullScreenPage_topBar_top: 18,
        navigationConfig_headerStyle_height: 110,
        navigationConfig_headerTitleStyle_marginLeft: 10,
        profileScreen_profileImage_top: 5,
        settingsScreen_container_top: -30,
        fullScreenPage_landscapeContainer_paddingLeft_Left: 180,
        fullScreenPage_landscapeContainer_paddingRight_Left: 170,
        fullScreenPage_landscapeContainer_paddingLeft_Right: 180,
        fullScreenPage_landscapeContainer_paddingRight_Right: 170,
        fullScreenPage_landscapeContainer_paddingTop: 40,
    },
    {
        fullScreenPage_topBar_left: 20,
        fullScreenPage_topBar_right: 20,
        fullScreenPage_topBar_top: 18,
        navigationConfig_headerStyle_height: 110,
        navigationConfig_headerTitleStyle_marginLeft: 10,
        profileScreen_profileImage_top: 5,
        settingsScreen_container_top: -30,
        fullScreenPage_landscapeContainer_paddingLeft_Left: 180,
        fullScreenPage_landscapeContainer_paddingRight_Left: 170,
        fullScreenPage_landscapeContainer_paddingLeft_Right: 180,
        fullScreenPage_landscapeContainer_paddingRight_Right: 170,
        fullScreenPage_landscapeContainer_paddingTop: 40,
    },
    {
        fullScreenPage_topBar_left: 20,
        fullScreenPage_topBar_right: 20,
        fullScreenPage_topBar_top: 18,
        navigationConfig_headerStyle_height: 130,
        navigationConfig_headerTitleStyle_marginLeft: 20,
        profileScreen_profileImage_top: 15,
        settingsScreen_container_top: -20,
        fullScreenPage_landscapeContainer_paddingLeft_Left: 250,
        fullScreenPage_landscapeContainer_paddingRight_Left: 180,
        fullScreenPage_landscapeContainer_paddingLeft_Right: 250,
        fullScreenPage_landscapeContainer_paddingRight_Right: 180,
        fullScreenPage_landscapeContainer_paddingTop: 20,
    },
    {
        fullScreenPage_topBar_left: 30,
        fullScreenPage_topBar_right: 30,
        fullScreenPage_topBar_top: 25,
        navigationConfig_headerStyle_height: 130,
        navigationConfig_headerTitleStyle_marginLeft: 20,
        profileScreen_profileImage_top: 15,
        settingsScreen_container_top: -20,
        fullScreenPage_landscapeContainer_paddingLeft_Left: 250,
        fullScreenPage_landscapeContainer_paddingRight_Left: 180,
        fullScreenPage_landscapeContainer_paddingLeft_Right: 200,
        fullScreenPage_landscapeContainer_paddingRight_Right: 200,
        fullScreenPage_landscapeContainer_paddingTop: 20,
    },
    {
        fullScreenPage_topBar_left: 30,
        fullScreenPage_topBar_right: 30,
        fullScreenPage_topBar_top: 25,
        navigationConfig_headerStyle_height: 130,
        navigationConfig_headerTitleStyle_marginLeft: 20,
        profileScreen_profileImage_top: 15,
        settingsScreen_container_top: -20,
        fullScreenPage_landscapeContainer_paddingLeft_Left: 250,
        fullScreenPage_landscapeContainer_paddingRight_Left: 180,
        fullScreenPage_landscapeContainer_paddingLeft_Right: 250,
        fullScreenPage_landscapeContainer_paddingRight_Right: 180,
        fullScreenPage_landscapeContainer_paddingTop: 20,
    }
][getDeviceType()];
