import {getDeviceType} from "../../utilitaries/device.tsx";

export const __Sizes: any = [
    {
        fullScreenPage_topBar_left: 15,
        fullScreenPage_topBar_right: 15,
        fullScreenPage_topBar_top: 15,
        navigationConfig_headerStyle_height: 110,
        navigationConfig_headerTitleStyle_marginLeft: 10,
        profileScreen_profileImage_top: 5,
        settingsScreen_container_top: -30,
        fullScreenPage_landscapeContainer_paddingLeft: 180,
        fullScreenPage_landscapeContainer_paddingRight: 170,
        fullScreenPage_landscapeContainer_paddingTop: 40,
    },
    {
        fullScreenPage_topBar_left: 20,
        fullScreenPage_topBar_right: 20,
        fullScreenPage_topBar_top: 18,
        navigationConfig_headerStyle_height: 110,
        navigationConfig_headerTitleStyle_marginLeft: 10,
        profileScreen_profileImage_top: 5,
        settingsScreen_container_top: -30,
        fullScreenPage_landscapeContainer_paddingLeft: 180,
        fullScreenPage_landscapeContainer_paddingRight: 170,
        fullScreenPage_landscapeContainer_paddingTop: 40,
    },
    {
        fullScreenPage_topBar_left: 20,
        fullScreenPage_topBar_right: 20,
        fullScreenPage_topBar_top: 18,
        navigationConfig_headerStyle_height: 130,
        navigationConfig_headerTitleStyle_marginLeft: 20,
        profileScreen_profileImage_top: 15,
        settingsScreen_container_top: -20,
        fullScreenPage_landscapeContainer_paddingLeft: 250,
        fullScreenPage_landscapeContainer_paddingRight: 180,
        fullScreenPage_landscapeContainer_paddingTop: 10,
    },
    {
        fullScreenPage_topBar_left: 30,
        fullScreenPage_topBar_right: 30,
        fullScreenPage_topBar_top: 25,
        navigationConfig_headerStyle_height: 130,
        navigationConfig_headerTitleStyle_marginLeft: 20,
        profileScreen_profileImage_top: 15,
        settingsScreen_container_top: -20,
        fullScreenPage_landscapeContainer_paddingLeft: 250,
        fullScreenPage_landscapeContainer_paddingRight: 180,
        fullScreenPage_landscapeContainer_paddingTop: 10,
    },
    {
        fullScreenPage_topBar_left: 30,
        fullScreenPage_topBar_right: 30,
        fullScreenPage_topBar_top: 25,
        navigationConfig_headerStyle_height: 130,
        navigationConfig_headerTitleStyle_marginLeft: 20,
        profileScreen_profileImage_top: 15,
        settingsScreen_container_top: -20,
        fullScreenPage_landscapeContainer_paddingLeft: 250,
        fullScreenPage_landscapeContainer_paddingRight: 180,
        fullScreenPage_landscapeContainer_paddingTop: 10,
    }
][getDeviceType()];
